### ISSUE TITLE
MiniJava Grammar

### ISSUE THREAD

**Issue by innomadic** [christophevg/human-parser-generator#30]
Pardon my use of the issue tracker for a question. 

How does this section in the MiniJava Tutorial not produce a conflict

```
non-less-than-expression = and-expression 
                         | non-and-expression
                         ;
                         
and-expression           = lhs @ non-and-expression "&&" rhs @ non-less-than-expression ;

non-and-expression       = group-expression
                         | primary-expression
                         ;

group-expression = "(" expression ")" ;
```

Both and-expression and non-and-expression ultimately can lead with a group-expression, which means that they could both begin with a parenthesis.  Does the Human Parser Generator lookahead further that one token??  How is that configured?

**Comment by christophevg** [comment]
No problem. If you're right, it might be an issue that needs solving anyway ;-)

It's been a while I've been playing with grammars, so lets see ;-)

When trying to match a non-less-than-expression, the parser first tries to match an and-expression.
When trying to match that and-expression, it will try to match a non-and-expression, followed by "&&" and then a non-less-than-expression. The non-and-expression can be matched by a group-expression. Now let's imagine that now there is no "&&", meaning the parser will backtrack to the next alternative for non-less-than-expression. This indeed can be a group-expression (which we already matched, so it) will match again and will complete the non-and-expression, and thus also the non-less-than-expression.

So it feels like it will work ;-)

Now, it would always be interesting to see if you can come up with an example Mini Java program that illustrates this problem you see.

Feel free to correct me, as I said, it's been a while playing with parsers ;-)
